# Generated by Django 4.2.5 on 2023-09-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='us', max_length=2)),
                ('coupon_id', models.PositiveIntegerField(unique=True)),
                ('coupon_webshop_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField()),
                ('promotion_type', models.CharField(choices=[('percent-off', 'Percent Off'), ('buy-one-get-one', 'Buy One Get One'), ('dollar-off', 'Dollar Off'), ('free-gift', 'Free Gift'), ('free-shipping', 'Free Shipping')], default='percent-off', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('value', models.PositiveIntegerField()),
                ('webshop_id', models.CharField(max_length=255)),
            ],
        ),
    ]
