# Generated by Django 4.2.5 on 2023-09-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponstats', '0003_alter_coupon_coupon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='promotion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='couponstats.promotiontype'),
        ),
    ]
